import java.util.Arrays;

import com.coldraincn.cdcleet.easy.TwoSum;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        
        int[] nums={2, 7, 11, 15};
        int target=9;
        TwoSum twosum=new TwoSum();
        int[] result2=twosum.twoSum(nums, target);
        System.out.println(Arrays.toString(result2));
    }
}
